### ISSUE TITLE
Struggling to understand clock configuration

### ISSUE THREAD

**Issue by planetarian** [nukeykt/Nuked-OPN2-FPGA#1]
I'm trying to wrap my head around the structure of this, and the clock configuration in mdinterface.v has me a bit confused.

I'm not familiar with the PLL IP in use, which accepts a clock input and outputs MCLK -- is this being configured in the environment?
Is MCLK to be the 3438's operating frequency (e.g. near 7.67MHz)?
What is PHI/VCLK? I notice dff1-4 in mdinterface.v which appear to apply a simple prescaler of sorts to the clock, which appears to only be used by the prescaler module. Is PHI/VCLK itself the 6:1 FM clock or is it for something else?

**Comment by nukeykt** [comment]
MCLK is global clock to make entire system syncronous, Nuked-MD uses 107,387mhz.
PHI is actual FM synthesizer clock (i.e 7,67mhz).
MCLK should be at least 2x of PHI to work properly I think.

EDIT: mdinterface.v uses 53,693mhz

**Comment by planetarian** [comment]
I believe I understand now. So the dff1-4/VCLK applies a 7:1 reduction to get it right in line at 7.67MHz. That's perfect, thank you!
